version: "3"

services: 
    nodejs:
        build: ./server
        volumes:
            - ./server:/server
            - /home/ubuntu/addeliverynetwork/server/node_modules
        command: npm run start
        env_file: ./server/.env
        depends_on:
            - db
        restart: unless-stopped
        tty: true
        links: 
            - db
        networks: 
            - webappnetwork

   
    webserver:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - web-root:/var/www/html
            - ./server/nginx-conf:/etc/nginx/conf.d
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - dhparam:/etc/ssl/certs
        depends_on:
            - nodejs
        networks:
            - webappnetwork
    db:
        image: mongo
        ports: 
            - 27017:27017
        restart: always
        command: mongod

        volumes: 
            - data-node:/data/db
        networks: 
            - webappnetwork
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - webserver
        command: certonly --webroot --webroot-path=/var/www/html --email jjones@mrc.org --agree-tos --no-eff-email --force-renewal -d ads.mrc.org  -d www.ads.mrc.org
networks: 
    webappnetwork:
        driver: bridge

volumes:
    data-node:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: /home/ubuntu/addevliverynetwork/server/build/
            o: bind
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: /home/ubuntu/addevliverynetwork/server/dhparam/
            o: bind
